/*
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// A Backup Job.
type Backup struct {

	// Size of the snapshot
	SnapshotSize string `json:"snapshotSize,omitempty"`

	// The Volume this Backup was created from
	VolumeUri string `json:"volumeUri,omitempty"`

	// Any actions on this model will be performed as this user.
	RunAsUser string `json:"runAsUser,omitempty"`

	// Is the volume this Backup is associated with a bootable volume
	Bootable bool `json:"bootable,omitempty"`

	// Description of the Backup
	Description string `json:"description,omitempty"`

	// Human readable error message
	ErrorMessage string `json:"errorMessage,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`

	// The snapshot created by this Backup
	SnapshotUri string `json:"snapshotUri,omitempty"`

	// Multi-part name of the backup configuration.
	BackupConfigurationName string `json:"backupConfigurationName,omitempty"`

	// State of this resource.
	State string `json:"state,omitempty"`

	// Is the volume this Backup is associated with a shared volume
	Shared bool `json:"shared,omitempty"`

	// Human readable detailed error message
	DetailedErrorMessage string `json:"detailedErrorMessage,omitempty"`

	// ID used to tag other cloud resources
	TagId string `json:"tagId,omitempty"`

	// The multi-part name of the object. Object names can contain only alphanumeric characters, hyphens, underscores, @ and periods. Object names are case-sensitive.
	Name string `json:"name,omitempty"`
}
