/*
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type InstanceResponse struct {

	// Shows the default account for your identity domain.
	Account string `json:"account,omitempty"`

	// A dictionary of attributes to be made available to the instance. A value with the key \"userdata\" will be made available in an EC2-compatible manner.
	Attributes string `json:"attributes,omitempty"`

	// Boot order list.
	BootOrder []string `json:"boot_order,omitempty"`

	// A label assigned by the user to identify disks.
	DiskAttach string `json:"disk_attach,omitempty"`

	// The default domain to use for the hostname and for DNS lookups.
	Domain string `json:"domain,omitempty"`

	// Optional imagelistentry number (default will be used if not specified).
	Entry int32 `json:"entry,omitempty"`

	// The reason for the instance going to error state, if available.
	ErrorReason string `json:"error_reason,omitempty"`

	// SSH server fingerprint presented by the instance.
	Fingerprint string `json:"fingerprint,omitempty"`

	// The hostname for this instance.
	Hostname string `json:"hostname,omitempty"`

	// A dictionary of hypervisor-specific attributes.
	Hypervisor string `json:"hypervisor,omitempty"`

	// The format of the image.
	ImageFormat string `json:"image_format,omitempty"`

	// Name of imagelist to be launched.
	Imagelist string `json:"imagelist,omitempty"`

	// IP address of the instance.
	Ip string `json:"ip,omitempty"`

	// A label assigned by the user, specifically for defining inter-instance relationships.
	Label string `json:"label,omitempty"`

	// Name of this instance, generated by the server.
	Name string `json:"name,omitempty"`

	// Mapping of <device name> to network specifiers for virtual NICs to be attached to this instance.
	Networking string `json:"networking,omitempty"`

	// A list of strings specifying arbitrary tags on nodes to be matched on placement.
	PlacementRequirements []string `json:"placement_requirements,omitempty"`

	// The OS platform for the instance.
	Platform string `json:"platform,omitempty"`

	// The priority at which this instance will be run.
	Priority string `json:"priority,omitempty"`

	// Not used
	Quota string `json:"quota,omitempty"`

	// Reference to the QuotaReservation, to be destroyed with the instance.
	QuotaReservation string `json:"quota_reservation,omitempty"`

	// Resolvers to use instead of the default resolvers.
	Resolvers []string `json:"resolvers,omitempty"`

	// Add PTR records for the hostname.
	ReverseDns bool `json:"reverse_dns,omitempty"`

	// Type of instance, as defined on site configuration.
	Shape string `json:"shape,omitempty"`

	// Site to run on.
	Site string `json:"site,omitempty"`

	// SSH keys that will be exposed to the instance.
	Sshkeys []string `json:"sshkeys,omitempty"`

	// Start time of the instance.
	StartTime string `json:"start_time,omitempty"`

	// State of the instance.
	State string `json:"state,omitempty"`

	// List of dictionaries containing storage attachment Information.
	StorageAttachments []string `json:"storage_attachments,omitempty"`

	// Comma-separated list of strings used to tag the instance.
	Tags []string `json:"tags,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`

	// vCable for this instance.
	VcableId string `json:"vcable_id,omitempty"`

	// Specify if the devices created for the instance are virtio devices. If not specified, the default will come from the cluster configration file.
	Virtio bool `json:"virtio,omitempty"`

	// IP address and port of the VNC console for the instance.
	Vnc string `json:"vnc,omitempty"`
}
