/* 
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The request body contains details of the IP network that you want to create. 
type IpNetworkPostRequest struct {

	// Specify the size of the IP subnet. It is a range of IPv4 addresses assigned in the virtual network, in CIDR address prefix format.<p>While specifying the IP address prefix take care of the following points:<p>* These IP addresses aren't part of the common pool of Oracle-provided IP addresses used by the shared network.<p>* There's no conflict with the range of IP addresses used in another IP network, the IP addresses used your on-premises network, or with the range of private IP addresses used in the shared network. If IP networks with overlapping IP subnets are linked to an IP exchange, packets going to and from those IP networks are dropped.<p>* The upper limit of the CIDR block size for an IP network is /16.<p>Note: The first IP address of any IP network is reserved for the default gateway, the DHCP server, and the DNS server of that IP network. 
	IpAddressPrefix string `json:"ipAddressPrefix,omitempty"`

	// Specify the IP network exchange to which the IP network belongs. You can add an IP network to only one IP network exchange, but an IP network exchange can include multiple IP networks. An IP network exchange enables access between IP networks that have non-overlapping addresses, so that instances on these networks can exchange packets with each other without NAT. 
	IpNetworkExchange string `json:"ipNetworkExchange,omitempty"`

	// The three-part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) of the IP network. <p>Object names can contain only alphanumeric, underscore (_), dash (-), and period (.) characters. Object names are case-sensitive.
	Name string `json:"name,omitempty"`
}
