/*
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type LaunchPlanResponse struct {

	// <p>A list of instances.<p>Each instance is defined using the instance attributes.
	Instances []string `json:"instances,omitempty"`

	// <p>The relationships between various instances.<p>Valid values:<ul><li>same_node: The specified instances are created on the same physical server. This is useful if you want to ensure low latency across instances.</li><li>different_node: The specified instances aren't created on the same physical server. This is useful if you want to isolate instances for security or redundancy.</li></ul>
	Relationships []string `json:"relationships,omitempty"`
}
