/*
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The request body contains details of the machine image that you want to create.
type MachineImagePostRequest struct {

	// Two-part name of the account (<code>/Compute-<em>identity_domain</em>/cloud_storage</code> that contains the credentials and access details of the associated Oracle Storage Cloud Service instance.
	Account string `json:"account,omitempty"`

	// <p>An optional JSON object or dictionary of arbitrary attributes to be made available to the instance. These are user-defined tags. After defining attributes, you can view them from within an instance at http://192.0.0.192/. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=STCSG-GUID-268FE284-E5A0-4A18-BA58-345660925FB7\">Retrieving User-Defined Instance Attributes</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>.
	Attributes string `json:"attributes,omitempty"`

	// <code><em>image_file</em>.tar.gz</code>, where <code><em>image_file</em></code> is the .tar.gz name of the machine image file that you have uploaded to Oracle Storage Cloud Service. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-799D6F6D-BDED-4DDE-9B3D-BE23BE5F687F\">Uploading Machine Image Files to Oracle Storage Cloud Service</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>.
	File string `json:"file,omitempty"`

	// <p>The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive.
	Name string `json:"name,omitempty"`

	// <p>Set this to <code>true</code>. Indicates that the image file is available in Oracle Cloud Storage Service.
	NoUpload bool `json:"no_upload,omitempty"`
}
