/*
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type OrchestrationResponse struct {

	// Shows the default account for your identity domain.
	Account string `json:"account,omitempty"`

	// Description of this orchestration plan.
	Description string `json:"description,omitempty"`

	// The nested parameter <code>errors</code> shows which object in the orchestration has encountered an error. Empty if there are no errors.
	Info string `json:"info,omitempty"`

	// <p>The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).
	Name string `json:"name,omitempty"`

	// List of oplans. An object plan, or oplan, is a top-level orchestration attribute.
	Oplans []string `json:"oplans,omitempty"`

	// The relationship between the objects that are created by this orchestration.
	Relationships []string `json:"relationships,omitempty"`

	// The schedule for an orchestration consists of the start and stop dates and times.
	Schedule string `json:"schedule,omitempty"`

	// Shows the current status of the orchestration.
	Status string `json:"status,omitempty"`

	// This information is generally displayed at the end of the orchestration JSON. It indicates the time that the current view of the orchestration was generated. This information shows only when the orchestration is running.
	StatusTimestamp string `json:"status_timestamp,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`

	// Two-part name of the user (<code>/Compute-<em>identity_domain</em>/<em>user</em></code>) who has most recently taken an action on the orchestration.
	User string `json:"user,omitempty"`
}
