/* 
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type RestoreInput struct {

	// Description of the Restore
	Description string `json:"description,omitempty"`

	// The entire URI of the storage volume that should be created when the backup is restored. Ensure that another volume with the same URI does not exist.
	VolumeUri string `json:"volumeUri,omitempty"`

	// The multi-part name of the object. Object names can contain only alphanumeric characters, hyphens, underscores, @ and periods. Object names are case-sensitive.
	Name string `json:"name,omitempty"`

	// Multi-part name of the backup that you want to restore. The backup must be in the <code>completed</code> state.
	BackupName string `json:"backupName,omitempty"`
}
