/* 
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The request body contains details of the route that you want to update. 
type RoutePutRequest struct {

	// Specify 0,1, or 2 as the route's administrative distance. If you do not specify a value, the default value is 0. <p>The same prefix can be used in multiple routes. In this case, packets are routed over all the matching routes with the lowest administrative distance. In case there are multiple routes with the same lowest administrative distance, routing occurs over all these routes using ECMP.
	AdminDistance int32 `json:"adminDistance,omitempty"`

	// The IPv4 address prefix, in CIDR format, of the destination.
	IpAddressPrefix string `json:"ipAddressPrefix,omitempty"`

	// The three-part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) that you want to update. <p>Object names can contain only alphanumeric, underscore (_), dash (-), and period (.) characters. Object names are case-sensitive.
	Name string `json:"name,omitempty"`

	// Three-part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) of the virtual NIC set to route matching packets to. Routed flows are load-balanced among all the virtual NICs in the virtual NIC set.
	NextHopVnicSet string `json:"nextHopVnicSet,omitempty"`
}
