/* 
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The request body contains details of the security list that you want to update. 
type SecListPutRequest struct {

	// <p>A description of the security list.
	Description string `json:"description,omitempty"`

	// <p>The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).<p>
	Name string `json:"name,omitempty"`

	// <p>The policy for outbound traffic from the security list. You can specify one of the following values:<ul><li><code>deny</code>: Packets are dropped. No response is sent.</li><li><code>reject</code>: Packets are dropped, but a response is sent.</li><li><code>permit</code>(default): Packets are allowed.</li>
	OutboundCidrPolicy string `json:"outbound_cidr_policy,omitempty"`

	// <p>The policy for inbound traffic to the security list. You can specify one of the following values:<ul><li><code>deny</code>(default): Packets are dropped. No response is sent.</li><li><code>reject</code>: Packets are dropped, but a response is sent.</li><li><code>permit</code>: Packets are allowed. This policy effectively turns off the firewall for all instances in this security list.</li></ul>
	Policy string `json:"policy,omitempty"`
}
