/* 
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

// The request body contains details of the storage volume that you want to create. 
type StorageVolumePostRequest struct {

	// <p>A boolean field that indicates whether the storage volume can be used as the boot disk for an instance.<p>The default value is <code>false</code>.<p>If you set the value to <code>true</code>, then you must specify values for the following parameters:<ul><li><code>imagelist</code><p>The machine image that you want to extract on to the storage volume that you're creating.</li><li><code>imagelist_entry</code><p>(Optional) The version of the image list entry that you want to extract. The default value is 1.</li></ul>
	Bootable bool `json:"bootable,omitempty"`

	// <p>The description of the storage volume.
	Description string `json:"description,omitempty"`

	// <p>The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive.
	Name string `json:"name,omitempty"`

	// Specify the operating system platform for a bootable storage volume, such as Linux or Windows.
	Platform string `json:"platform,omitempty"`

	// <p>The storage-pool property.<p>For storage volumes that require low latency and high IOPS, such as for storing database files, specify <code>/oracle/public/storage/latency</code>.<p>For all other storage volumes, specify <code>/oracle/public/storage/default</code>.
	Properties []string `json:"properties,omitempty"`

	// <p>The size of this storage volume. Use one of the following abbreviations for the unit of measurement:<ul><li><code>B</code> or <code>b</code> for bytes</li><li><code>K</code> or <code>k</code> for kilobytes</li><li><code>M</code> or <code>m</code> for megabytes</li><li><code>G</code> or <code>g</code> for gigabytes</li><li><code>T</code> or <code>t</code> for terabytes</li></ul><p>For example, to create a volume of size 10 gigabytes, you can specify <code>10G</code>, or <code>10240M</code>, or <code>10485760K</code>, and so on.<p>The allowed range is from 1 GB to 2 TB, in increments of 1 GB. <p>If you are creating a bootable storage volume, ensure that the size of the storage volume is greater than the size of the machine image that you want to extract on to the storage volume.<p>If you are creating this storage volume from a storage snapshot, ensure that the size of the storage volume that you create is greater than the size of the storage snapshot.
	Size string `json:"size,omitempty"`

	// Multipart name of the storage volume snapshot if this storage volume is a clone.
	Snapshot string `json:"snapshot,omitempty"`

	// Account of the parent snapshot from which the storage volume is restored.
	SnapshotAccount string `json:"snapshot_account,omitempty"`

	// Id of the parent snapshot from which the storage volume is restored or cloned.
	SnapshotId string `json:"snapshot_id,omitempty"`

	// <p>Strings that you can use to tag the storage volume.
	Tags []string `json:"tags,omitempty"`
}
