/*
 * REST API for Oracle Compute Cloud Service (IaaS)
 *
 * Use the Oracle Compute Cloud Service REST API to provision and manage instances and the associated resources
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type VpnEndpointResponse struct {

	// IP address of the VPN gateway in your data center through which you want to connect to the Oracle Cloud VPN gateway.
	CustomerVpnGateway string `json:"customer_vpn_gateway,omitempty"`

	// <code>true</code> indicates that the VPN endpoint is enabled and a connection is established immediately, if possible.
	Enabled bool `json:"enabled,omitempty"`

	// Two-part name of the object (<code><em>/Compute-acme/object</em></code>)
	Name string `json:"name,omitempty"`

	// Pre-shared VPN key.
	Psk string `json:"psk,omitempty"`

	// List of routes (CIDR prefixes) that are reachable through this VPN tunnel.
	ReachableRoutes []string `json:"reachable_routes,omitempty"`

	// Current status of the VPN tunnel.
	Status string `json:"status,omitempty"`

	// Describes the current status of the VPN tunnel.
	StatusDesc string `json:"status_desc,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`

	// Statistics of VPN tunnels
	VpnStatistics string `json:"vpn_statistics,omitempty"`
}
